# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL: 'https://glenn-roberts.com'
defaultContentLanguage: en
languageCode: en

enableRobotsTXT: true
paginate: 10
summaryLength: 0

permalinks:
  posts: '/blog/:year/:month/:day/:slug/'

outputs:
  home:
    - HTML
    - RSS
    - JSON

# https://github.com/gohugoio/hugo/issues/9811
security:
  exec:
    osEnv:
      - '(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$'
      - ^ASDF_DIR$
      - ^HOME$
